### ISSUE TITLE
option to show only thumnail and keep the thumnail original size?

### ISSUE THREAD

**Issue by littleblack111** [vimpostor/blobdrop#10]
### Describe the bug

not a bug, a suggestion

**Comment by vimpostor** [comment]
I am not sure how that would look like, could you elaborate?

Also what do you mean with original thumbnail size? If you mean the size of the source image, then that would look pretty bad as soon as the images get a bit larger.

**Comment by littleblack111** [comment]
try dragon, the --icon-only option and --thumb-size option

**Comment by vimpostor** [comment]
Ok, but could you briefly explain the use case for manually specifying the thumbnail size with `--thumb-size`? The images already scale very well with your screen, as Qt has first-class High DPI support. Is there something I can improve with the image size in general instead?

**Comment by littleblack111** [comment]
its... pretty small... or maybe a --thumb-scale-size?
